
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            # sudo apt update
            # sudo apt upgrade -y
            docker -version
            chmod +x run_docker.sh
            ./run_docker.sh

      - run:
          name: Hadolint test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            /bin/hadolint --ignore DL3013 Dockerfile

      - run:
          name: Making predictions
          command: |
            chmod +x make_prediction.sh
            ./make_prediction.sh
 