version: 2.1

jobs:
  build-hadolint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths: 
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            /bin/hadolint --ignore DL3013 Dockerfile

  build-docker:
    docker:
      - image: cimg/base:2023.07
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            sudo apt update
            sudo apt upgrade -y
            sudo apt install python3.10-venv
      - run:
          name: Build Docker image
          command: |
            chmod +x run_docker.sh
            ./run_docker.sh

      - run:
          name: Making predictions
          command: |
            docker ps -a
            sudo netstat -tulpn | grep :80
            chmod +x make_prediction.sh
            ./make_prediction.sh
 
workflows:
  Build-Docker:
    jobs:
      - build-hadolint
      - build-docker:
          requires: [build-hadolint]