version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.07
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            wget https://launchpad.net/ubuntu/+source/docker.io/20.10.2-0ubuntu1~18.04.2/+build/21335731/+files/docker.io_20.10.2-0ubuntu1~18.04.2_arm64.deb
            sudo dpkg -i docker.io_20.10.2-0ubuntu1~18.04.2_arm64.deb
            rm docker.io_20.10.2-0ubuntu1~18.04.2_arm64.deb
            sudo apt install containerd=1.5.2-0ubuntu1~18.04.3
            sudo apt update
            sudo apt upgrade -y
      - run:
          name: Build Docker image
          command: |
            chmod +x run_docker.sh
            ./run_docker.sh

      - run:
          name: Hadolint test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            /bin/hadolint --ignore DL3013 Dockerfile

      - run:
          name: Making predictions
          command: |
            chmod +x make_prediction.sh
            ./make_prediction.sh
 
workflows:
  Build-Docker:
    jobs:
      - build